<#
.SYNOPSIS
    Generates crates/m68hc16-asm/src/isa/table.rs from docs/spec/isa-table.tsv.
    The table is the canonical HC16 encoding ground truth (derived from the real
    MASM via the golden oracle). Do not hand-edit the generated file.
#>
[CmdletBinding()]
param(
    [string]$Tsv = "$PSScriptRoot\..\..\docs\spec\isa-table.tsv",
    [string]$OutRs = "$PSScriptRoot\..\..\crates\m68hc16-asm\src\isa\table.rs"
)
$ErrorActionPreference = 'Stop'

# TSV mode -> Rust Mode expression.
$MAP = @{
    'inh'='Mode::Inherent'; 'imm8'='Mode::Imm8'; 'imm16'='Mode::Imm16'
    'ext'='Mode::Ext'; 'ext20'='Mode::Ext20'
    'ind8x'='Mode::Ind8(IdxReg::X)'; 'ind8y'='Mode::Ind8(IdxReg::Y)'; 'ind8z'='Mode::Ind8(IdxReg::Z)'
    'ind16x'='Mode::Ind16(IdxReg::X)'; 'ind16y'='Mode::Ind16(IdxReg::Y)'; 'ind16z'='Mode::Ind16(IdxReg::Z)'
    'ind20x'='Mode::Ind20(IdxReg::X)'; 'ind20y'='Mode::Ind20(IdxReg::Y)'; 'ind20z'='Mode::Ind20(IdxReg::Z)'
    'eindx'='Mode::EInd(IdxReg::X)'; 'eindy'='Mode::EInd(IdxReg::Y)'; 'eindz'='Mode::EInd(IdxReg::Z)'
    'rel8'='Mode::Rel8'; 'rel16'='Mode::Rel16'
    'bit'='Mode::BitExt'; 'bitbr'='Mode::BitBrExt'; 'reg'='Mode::RegList'
    'bitix'='Mode::BitInd(IdxReg::X)'; 'bitiy'='Mode::BitInd(IdxReg::Y)'; 'bitiz'='Mode::BitInd(IdxReg::Z)'
    'bitix16'='Mode::BitInd16(IdxReg::X)'; 'bitiy16'='Mode::BitInd16(IdxReg::Y)'; 'bitiz16'='Mode::BitInd16(IdxReg::Z)'
    'bitwx'='Mode::BitIndW(IdxReg::X)'; 'bitwy'='Mode::BitIndW(IdxReg::Y)'; 'bitwz'='Mode::BitIndW(IdxReg::Z)'
    'bitbrix'='Mode::BitBrInd(IdxReg::X)'; 'bitbriy'='Mode::BitBrInd(IdxReg::Y)'; 'bitbriz'='Mode::BitBrInd(IdxReg::Z)'
    'bitbrix16'='Mode::BitBrInd16(IdxReg::X)'; 'bitbriy16'='Mode::BitBrInd16(IdxReg::Y)'; 'bitbriz16'='Mode::BitBrInd16(IdxReg::Z)'
    'mov_mm'='Mode::MovMm'; 'mov_ix'='Mode::MovIdxExt'; 'mov_xi'='Mode::MovExtIdx'; 'mac'='Mode::Mac'
}

# Stable per-mnemonic mode ordering for readable output.
$ORDER = @('inh','imm8','imm16','ext','ext20','ind8x','ind8y','ind8z','ind16x','ind16y','ind16z',
           'ind20x','ind20y','ind20z',
           'eindx','eindy','eindz','rel8','rel16','bit','bitix','bitiy','bitiz',
           'bitix16','bitiy16','bitiz16','bitwx','bitwy','bitwz',
           'bitbr','bitbrix','bitbriy','bitbriz','bitbrix16','bitbriy16','bitbriz16',
           'reg','mov_mm','mov_ix','mov_xi','mac')
$rank = @{}; for ($i=0; $i -lt $ORDER.Count; $i++) { $rank[$ORDER[$i]] = $i }

$byMn = [ordered]@{}
Get-Content $Tsv | Select-Object -Skip 1 | ForEach-Object {
    $c = $_ -split "`t"
    if ($c.Count -lt 4) { return }
    $mn = $c[0]; $mode = $c[1]; $prefix = $c[2]; $oplen = [int]$c[3]
    if (-not $MAP.ContainsKey($mode)) { throw "Unmapped mode '$mode' for $mn" }
    if (-not $byMn.Contains($mn)) { $byMn[$mn] = New-Object System.Collections.Generic.List[object] }
    $byMn[$mn].Add([pscustomobject]@{ mode=$mode; prefix=$prefix; oplen=$oplen }) | Out-Null
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// @generated by tools/oracle/Generate-IsaRust.ps1 from docs/spec/isa-table.tsv')
[void]$sb.AppendLine('// Source of truth is the real Motorola MASM (via the DOSBox golden oracle).')
[void]$sb.AppendLine('// Do not edit by hand; re-run the generator instead.')
[void]$sb.AppendLine('#![cfg_attr(rustfmt, rustfmt_skip)]')
[void]$sb.AppendLine('use super::{InsnDef, ModeEntry, Mode, IdxReg};')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('pub static INSTRUCTIONS: &[InsnDef] = &[')

foreach ($mn in $byMn.Keys) {
    $modes = $byMn[$mn] | Sort-Object { if ($rank.ContainsKey($_.mode)) { $rank[$_.mode] } else { 99 } }
    [void]$sb.AppendLine("    InsnDef { mnemonic: `"$mn`", modes: &[")
    foreach ($m in $modes) {
        $bytes = @($m.prefix -split ' ' | Where-Object { $_ -ne '' } | ForEach-Object { '0x' + $_ })
        $arr = '&[' + ($bytes -join ', ') + ']'
        [void]$sb.AppendLine("        ModeEntry { mode: $($MAP[$m.mode]), prefix: $arr, operand_len: $($m.oplen) },")
    }
    [void]$sb.AppendLine('    ] },')
}
[void]$sb.AppendLine('];')

$outDir = Split-Path $OutRs
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }
[System.IO.File]::WriteAllText($OutRs, $sb.ToString())
$count = ($byMn.Keys).Count
Write-Host "Generated $OutRs : $count mnemonics."
